learning_rate : .0001
optimizer : 'Adam'
batch_size : 32
model : 'None'
dataset_path : 'None'
epochs : 10
loss_function : 'None'
model_save_path : 'None'
graph_save_path : 'None'
load_existing_model : False
model_load_path : True