learning_rate : .0001
optimizer : 'Adam'
batch_size : 32
model : 'CNN_AE_MLP'
dataset_path : 'C:\Users\bisch\Downloads\chbmit.csv'
epochs : 5
model_save_path : 'None'
graph_save_path : 'None'
load_existing_model : False
model_load_path : True